<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ShutdownTimer</AssemblyName>
    <RootNamespace>ShutdownTimer</RootNamespace>
    <ApplicationIcon>Assets\ShutdownTimer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\ShutdownTimer.ico" />
    <Resource Include="Assets\app-logo.png" />
    <Content Include="background.mp4" Condition="Exists('background.mp4')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
